////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2016 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 20.16Release
// Tag = production/akw/20.16.00-0-gce20b51
////////////////////////////////////////////////////////////////////////////////


#include <iostream>
#include "fit_encode.hpp"
#include "fit_crc.hpp"

namespace fit
{
Encode::Encode()
    : Encode( ProtocolVersion::V10 ) {}

Encode::Encode( ProtocolVersion version )
    : dataSize( 0 )
      , file( nullptr )
      , version( version )
      , validator( version ) {}

void Encode::Open(std::iostream &file)
{
    this->file = &file;
    WriteFileHeader();
}

void Encode::Write( const MesgDefinition& mesgDef )
{
    if ( !file )
        return;

    if ( !validator.ValidateMesgDefn( mesgDef ) )
        return;

    dataSize += mesgDef.Write( *file );
    lastMesgDefinition[mesgDef.GetLocalNum()] = mesgDef;
}

void Encode::Write( const Mesg& mesg )
{
    MesgDefinition mesgDefinition( mesg );

    if ( !file )
        return;

    if ( !validator.ValidateMesg( mesg ) )
        return;

    if ( !lastMesgDefinition[mesg.GetLocalNum()].Supports( mesgDefinition ) )
        Write( mesgDefinition );

    dataSize += mesg.Write( *file, &( lastMesgDefinition[mesg.GetLocalNum()] ) );
}

void Encode::Write( const std::vector<Mesg>& mesgs )
{
    for ( std::vector<Mesg>::size_type i = 0; i < mesgs.size(); i++ )
        Write( mesgs[i] );
}

FIT_BOOL Encode::Close( void )
{
    FIT_UINT32 fileBytesLeft = FIT_FILE_HDR_SIZE + dataSize;
    FIT_UINT16 crc = 0;

    if ( !file )
        return FIT_FALSE;

    WriteFileHeader();

    file->seekg( 0, std::ios::beg );

    while ( fileBytesLeft > 0 )
    {
        FIT_UINT8 byte = ( FIT_UINT8 )file->get();

        if ( file->eof() )
            return FIT_FALSE; // File smaller than expected.

        crc = CRC::Get16( crc, byte );
        fileBytesLeft--;
    }

    file->seekp( 0, std::ios::end );
    file->put( crc & 0xFF );
    file->put( ( char )( crc >> 8 ) );

    return FIT_TRUE;
}

void Encode::OnMesg( Mesg& mesg )
{
    Write( mesg );
}

void Encode::OnMesgDefinition( MesgDefinition& mesgDef )
{
    Write( mesgDef );
}

void Encode::WriteFileHeader()
{
    if ( !file )
        return;

    // Serialize the header field-by-field rather than dumping the FIT_FILE_HDR
    // struct: the struct carries compiler alignment padding (its sizeof is not
    // 14), so writing it raw produces a mis-laid-out header — the ".FIT"
    // signature and data_size land at the wrong offsets, which strict parsers
    // (Strava: "Unrecognized file type") reject. Explicit little-endian bytes
    // guarantee the on-disk layout matches the FIT spec.
    const FIT_UINT16 profileVersion  = FIT_PROFILE_VERSION;
    const FIT_UINT8  protocolVersion = fit::versionMap.at( version ).GetVersionByte();

    FIT_UINT8 header[FIT_FILE_HDR_SIZE];
    header[0]  = FIT_FILE_HDR_SIZE;                            // header_size
    header[1]  = protocolVersion;                             // protocol_version
    header[2]  = ( FIT_UINT8 )(  profileVersion        & 0xFF );  // profile_version (LE)
    header[3]  = ( FIT_UINT8 )( ( profileVersion >> 8 ) & 0xFF );
    header[4]  = ( FIT_UINT8 )(  dataSize        & 0xFF );        // data_size (LE)
    header[5]  = ( FIT_UINT8 )( ( dataSize >> 8  ) & 0xFF );
    header[6]  = ( FIT_UINT8 )( ( dataSize >> 16 ) & 0xFF );
    header[7]  = ( FIT_UINT8 )( ( dataSize >> 24 ) & 0xFF );
    header[8]  = '.';                                          // data_type ".FIT"
    header[9]  = 'F';
    header[10] = 'I';
    header[11] = 'T';
    const FIT_UINT16 headerCrc = CRC::Calc16( header, 12 );    // CRC over the 12 bytes above
    header[12] = ( FIT_UINT8 )(  headerCrc       & 0xFF );     // crc (LE)
    header[13] = ( FIT_UINT8 )( ( headerCrc >> 8 ) & 0xFF );

    file->seekp( 0, std::ios::beg );
    file->write( ( const char * )header, FIT_FILE_HDR_SIZE );
}
} // namespace fit

